/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saler
 */
public class Manutencoes extends javax.swing.JFrame {

    int contador = 1;
    /**
     * Creates new form Manutencoes
     */
    public Manutencoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        h2Titulo = new javax.swing.JLabel();
        jlIdManutencao = new javax.swing.JLabel();
        jtIdManutencao = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbRemover = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ljIcon = new javax.swing.JLabel();
        jlProjetor = new javax.swing.JLabel();
        jcbProjetor = new javax.swing.JComboBox<>();
        jtDataManutencao = new javax.swing.JFormattedTextField();
        jlDataManutencao = new javax.swing.JLabel();
        jcbTecnico = new javax.swing.JComboBox<>();
        jlTecnico = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProjetores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));

        jPanel2.setBackground(new java.awt.Color(0, 92, 184));
        jPanel2.setPreferredSize(new java.awt.Dimension(1440, 300));

        h2Titulo.setFont(new java.awt.Font("Dialog", 1, 64)); // NOI18N
        h2Titulo.setForeground(new java.awt.Color(255, 255, 255));
        h2Titulo.setText("Manutenções");

        jlIdManutencao.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jlIdManutencao.setText("Id de Manuteção");

        jtIdManutencao.setBackground(new java.awt.Color(255, 255, 255));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.setName("JbpCadastrar"); // NOI18N
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbRemover.setText("Remover");
        jbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ljIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/icon2.png"))); // NOI18N

        jlProjetor.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jlProjetor.setText("Projetor");

        jcbProjetor.setBackground(new java.awt.Color(255, 255, 255));
        jcbProjetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbProjetor.setBorder(null);
        jcbProjetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProjetorActionPerformed(evt);
            }
        });
        jcbProjetor.setSelectedIndex(-1);

        jtDataManutencao.setBackground(new java.awt.Color(255, 255, 255));
        try {
            jtDataManutencao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/## ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtDataManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDataManutencaoActionPerformed(evt);
            }
        });

        jlDataManutencao.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jlDataManutencao.setText("Data da Manutenção");

        jcbTecnico.setBackground(new java.awt.Color(255, 255, 255));
        jcbTecnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTecnico.setBorder(null);
        jcbTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTecnicoActionPerformed(evt);
            }
        });
        jcbTecnico.setSelectedIndex(-1);

        jlTecnico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jlTecnico.setText("Técnico");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(ljIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(h2Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlIdManutencao)
                            .addComponent(jtIdManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbProjetor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlProjetor))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTecnico))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtDataManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDataManutencao)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(h2Titulo)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ljIcon))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlProjetor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbProjetor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlTecnico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbTecnico))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlIdManutencao)
                        .addGap(10, 10, 10)
                        .addComponent(jtIdManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jtDataManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlDataManutencao))))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbAlterar)
                    .addComponent(jbRemover))
                .addGap(55, 55, 55))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tbProjetores.setBackground(new java.awt.Color(255, 255, 255));
        tbProjetores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idManutencao", "Projetor", "Técnico", "Data da Manutenção"
            }
        ));
        tbProjetores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProjetoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProjetores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1423, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbProjetoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProjetoresMouseClicked
        if (tbProjetores.getSelectedRow() != -1) {
            jtIdManutencao.setText(tbProjetores.getValueAt(tbProjetores.getSelectedRow(), 0).toString());
            jcbProjetor.setSelectedItem(tbProjetores.getValueAt(tbProjetores.getSelectedRow(), 1).toString());
            jcbTecnico.setSelectedItem(tbProjetores.getValueAt(tbProjetores.getSelectedRow(), 2).toString());
            jtDataManutencao.setText(tbProjetores.getValueAt(tbProjetores.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_tbProjetoresMouseClicked

    private void jcbTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTecnicoActionPerformed

    private void jcbProjetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProjetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbProjetorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverActionPerformed
        if (tbProjetores.getSelectedRow() != -1) {
            DefaultTableModel tbcadastro = (DefaultTableModel) tbProjetores.getModel();
            tbcadastro.removeRow((tbProjetores.getSelectedRow()));
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Cadastro para excluir!");
        }
    }//GEN-LAST:event_jbRemoverActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        //verifica se há coluna selecionada
        if (tbProjetores.getSelectedRow() != -1) {
            tbProjetores.setValueAt(jtIdManutencao.getText(), tbProjetores.getSelectedRow(), 0);
            tbProjetores.setValueAt(jcbProjetor.getSelectedItem(), tbProjetores.getSelectedRow(), 1);
            tbProjetores.setValueAt(jcbTecnico.getSelectedItem(), tbProjetores.getSelectedRow(), 2);
            tbProjetores.setValueAt(jtDataManutencao.getText(), tbProjetores.getSelectedRow(), 3);
            limparCampos();
            tbProjetores.setSelectionMode(-1);//deseleciona a linha selecionada
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Cadastro para Alterar!");
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        DefaultTableModel tbcadastro = (DefaultTableModel) tbProjetores.getModel();
        Object[] dados = {
            contador++,
            jcbProjetor.getSelectedItem(),
            jcbTecnico.getSelectedItem(),
            jtDataManutencao.getText()
        };
        tbcadastro.addRow(dados);
        limparCampos();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jtDataManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDataManutencaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDataManutencaoActionPerformed

    private void limparCampos() {
        jtIdManutencao.setText(null);
        jcbProjetor.setSelectedIndex(-1);
        jcbTecnico.setSelectedIndex(-1);
        jtDataManutencao.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manutencoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manutencoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manutencoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manutencoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manutencoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel h2Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbRemover;
    private javax.swing.JComboBox<String> jcbProjetor;
    private javax.swing.JComboBox<String> jcbTecnico;
    private javax.swing.JLabel jlDataManutencao;
    private javax.swing.JLabel jlIdManutencao;
    private javax.swing.JLabel jlProjetor;
    private javax.swing.JLabel jlTecnico;
    private javax.swing.JFormattedTextField jtDataManutencao;
    private javax.swing.JTextField jtIdManutencao;
    private javax.swing.JLabel ljIcon;
    private javax.swing.JTable tbProjetores;
    // End of variables declaration//GEN-END:variables
}
